# Spring容器相关配置信息
spring:
  application:
    # Spring应用程序名称
    name: background-workbench
# 服务器端口
server:
  port: 9090


# Dubbo相关配置信息
dubbo:
  scan:
    # 控制器扫描，告知Dubbo控制器在哪里，以便扫描
    basePackages: com.ants.backgroundworkbench.controller
  # Dubbo应用程序Bean配置
  application:
    # 在Dubbo中应用程序的编号
    id: background-workbench
    # 在Dubbo中应用程序名称
    name: background-workbench
  # 在注册中心中和生产者使用哪个协议，用来进行识别功能
  protocol:
    id: dubbo
    name: dubbo
    # 协议端口
    port: 12345
    # 序列化
    serialization: kryo
  # 注册中心配置相关信息
  registry:
    id: zookeeper
    address: zookeeper://192.168.43.86:2181?backup=192.168.43.86:2182,192.168.43.86:2183

# Dubbo端点允许开启
endpoints:
  dubbo:
    enabled: true

management:
  # 开启所有的Dubbo的端点
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo状态检查器
  health:
    dubbo:
      status:
        # 状态检查器名称默认值(默认值:“memory”，“load”)
        defaults: memory
  endpoints:
    web:
      exposure:
        include: "*"
